backend:
  name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: Course
    label: Course
    folder: courses
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: price, label: Price}
      - { name: location, label: Location}